compute_environment: LOCAL_MACHINE
debug: false
deepspeed_config:
  gradient_accumulation_steps: 1
  offload_optimizer_device: cpu
  offload_param_device: cpu
  zero3_init_flag: true
  zero_stage: 3
  zero_optimization:
    stage: 3
    allgather_partitions: true
    allgather_bucket_size: 1e7
    reduce_scatter: true
    reduce_bucket_size: 1e7
    contiguous_gradients: true
    overlap_comm: true
    stage3_prefetch_bucket_size: 1e7
    stage3_param_persistence_threshold: 1e6
    stage3_max_live_parameters: 1e9
    stage3_max_reuse_distance: 1e9
    sub_group_size: 1e9
  activation_checkpointing:
    partition_activations: true
    cpu_checkpointing: true
    contiguous_memory_optimization: true
    synchronize_checkpoint_boundary: true
  offload_param:
    device: cpu
    pin_memory: false
  offload_optimizer:
    device: cpu
    pin_memory: false
  stage3_gather_16bit_weights_on_model_save: true
  zero_allow_untested_optimizer: true
distributed_type: DEEPSPEED
downcast_bf16: 'no'
enable_cpu_affinity: false
machine_rank: 0
main_training_function: main
mixed_precision: bf16
num_machines: 1
num_processes: 8
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false
